"""increase unmapped_rows column sizes

Revision ID: 5e6b677c499a
Revises: 001
Create Date: 2026-02-17 23:33:32.885937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e6b677c499a'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('biomarker_registry', 'is_derived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('biomarker_registry', 'aliases',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('lab_events', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('lab_events', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('unmapped_rows', 'raw_value',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('unmapped_rows', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unmapped_rows', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('unmapped_rows', 'raw_value',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('lab_events', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('lab_events', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('biomarker_registry', 'aliases',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('biomarker_registry', 'is_derived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
