"""add flag column to lab_events

Revision ID: b533b484a72b
Revises: 7c9083550134
Create Date: 2026-02-18 05:25:54.627140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b533b484a72b'
down_revision: Union[str, None] = '7c9083550134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_events', sa.Column('flag', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_events', 'flag')
    # ### end Alembic commands ###
